# Generated by Django 6.0.2 on 2026-02-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselingmessage',
            old_name='read_flag',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='counselingmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counselingmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
