# Generated by Django 6.0.2 on 2026-02-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0002_rename_read_flag_counselingmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencelog',
            name='is_snoozed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatientGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_streak_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to='adherence.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adherence_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adherence.adherencelog')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='adherence.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyConsistencyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('badge_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=20)),
                ('bonus_points', models.IntegerField(default=0)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_badges', to='adherence.patientprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'week_start_date'), name='unique_weekly_badge')],
            },
        ),
    ]
