# Generated by Django 6.0.2 on 2026-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0003_adherencelog_is_snoozed_patientgamificationprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('mental', 'Mental'), ('physical', 'Physical'), ('emotional', 'Emotional'), ('spiritual', 'Spiritual')], max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
