# Generated by Django 6.0.2 on 2026-02-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0004_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
