# Generated by Django 6.0.2 on 2026-02-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0005_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherencelog',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('taken', 'Taken'), ('missed', 'Missed'), ('snoozed', 'Snoozed')], max_length=20),
        ),
    ]
