# Generated by Django 6.0.2 on 2026-02-18 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0006_alter_adherencelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='pills_per_dose',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('total_pills', models.IntegerField(default=30)),
                ('current_pills', models.IntegerField(default=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='adherence.patientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='adherence.prescription'),
        ),
    ]
