# Generated by Django 6.0.2 on 2026-02-24 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0007_medicationschedule_pills_per_dose_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherence_window_before_hours', models.FloatField(default=1.0, help_text='Hours before scheduled time a dose can be marked taken')),
                ('adherence_window_after_hours', models.FloatField(default=1.0, help_text='Hours after scheduled time a dose can be marked taken')),
                ('vl_suppression_threshold', models.IntegerField(default=1000, help_text='Viral load value threshold for suppression')),
                ('adherence_high_threshold', models.FloatField(default=90.0, help_text='Percentage threshold for high adherence')),
                ('vl_review_window_days', models.IntegerField(default=60, help_text='Days to look back for adherence review')),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email_notifs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='push_notifs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='whatsapp_notifs',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ViralLoadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('viral_load_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_viral_loads', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viral_load_results', to='adherence.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ViralLoadReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_start_date', models.DateField()),
                ('review_end_date', models.DateField()),
                ('adherence_percentage', models.FloatField(default=0.0)),
                ('missed_doses', models.IntegerField(default=0)),
                ('late_doses', models.IntegerField(default=0)),
                ('flagged_logs', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('CONSISTENT_AND_CONTROLLED', 'Consistent and Controlled'), ('LIKELY_NON_ADHERENCE', 'Likely Non-Adherence'), ('POSSIBLE_REPORTING_OR_TREATMENT_ISSUE', 'Possible Reporting or Treatment Issue'), ('SHORT_TERM_NON_ADHERENCE', 'Short-Term Non-Adherence'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('viral_load_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='adherence.viralloadresult')),
            ],
        ),
    ]
