# Generated by Django 6.0.2 on 2026-02-24 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0008_systemsettings_patientprofile_email_notifs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
