# Generated by Django 6.0.2 on 2026-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0009_alter_prescription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralloadresult',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
