# Generated by Django 6.0.2 on 2026-02-25 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0010_viralloadresult_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('adherence_report', 'Adherence Report'), ('viral_load_report', 'Viral Load Report')], default='text', max_length=50),
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('report_type', models.CharField(choices=[('adherence_report', 'Adherence Report'), ('viral_load_report', 'Viral Load Report')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='adherence.patientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='counselingmessage',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_to_messages', to='adherence.reportfile'),
        ),
    ]
